import type { NetworkSummary } from '@/types/api';
export const networkSummary: NetworkSummary = {
  rate_sampled_sessions: 50,
  online_users: 52,
  online_vouchers: 40,
  stale_sessions: 3,
  sessions_today: 70,
  live_upload_bytes: 1000,
  live_download_bytes: 2000,
  live_traffic_bytes: 3000,
  today_upload_bytes: 4000,
  today_download_bytes: 5000,
  today_traffic_bytes: 9000,
  all_time_upload_bytes: 10000,
  all_time_download_bytes: 20000,
  all_time_traffic_bytes: 30000,
  upload_bytes_per_second: null,
  download_bytes_per_second: 1024,
  latest_accounting_at: new Date().toISOString(),
  router_counts: { online: 1, offline: 0, unknown: 1, awaiting_import: 1, inactive: 0 },
  routers: [
    { id: 'router-1', name: 'Main router', status: 'online', online_users: 52, last_seen_at: null },
  ],
  routers_total: 3,
  observed_at: new Date().toISOString(),
  freshness_seconds: 300,
  traffic_basis: 'cumulative_counters_for_sessions_active_today',
  source: 'radius_accounting',
};
