import type { Voucher } from '@/types/api';

/** Mirrors backend `perform_update` / `perform_destroy`: only pristine admin vouchers are editable. */
export function isEditable(voucher: Voucher): boolean {
  if (voucher.can_edit !== undefined) return voucher.can_edit;
  return (
    voucher.status === 'unused' &&
    voucher.agent === null &&
    voucher.generation_source !== 'customer'
  );
}

export function canDisable(voucher: Voucher): boolean {
  return ['unused', 'sold', 'used', 'active'].includes(voucher.status);
}

export function describeSource(voucher: Voucher): string {
  switch (voucher.generation_source) {
    case 'agent':
      return voucher.agent_name ? `Agent · ${voucher.agent_name}` : 'Agent';
    case 'customer':
      return 'Online purchase';
    default:
      return 'Generated by staff';
  }
}
