import { describe, expect, it } from 'vitest';
import type { Voucher } from '@/types/api';
import { canDisable, describeSource, isEditable } from './voucherRules';

const base: Voucher = {
  id: 1,
  username: 'u',
  plan: 1,
  plan_name: 'Daily',
  plan_duration: '24',
  price_display: '₦500',
  tenant: 2,
  tenant_name: 'T',
  agent: null,
  agent_name: null,
  status: 'unused',
  generation_source: 'admin',
  device_limit: 1,
  expires_at: null,
  activated_at: null,
  created_at: '2026-01-01T00:00:00Z',
};

describe('voucher rules (mirror backend perform_update/destroy)', () => {
  it('pristine admin vouchers are editable and disable-able', () => {
    expect(isEditable(base)).toBe(true);
    expect(canDisable(base)).toBe(true);
  });
  it('agent-issued vouchers are not editable', () => {
    expect(isEditable({ ...base, agent: 5, agent_name: 'chidi', generation_source: 'agent' })).toBe(
      false,
    );
    expect(
      describeSource({ ...base, agent: 5, agent_name: 'chidi', generation_source: 'agent' }),
    ).toBe('Agent · chidi');
  });
  it('active vouchers can be disabled but not edited; expired/disabled neither', () => {
    expect(isEditable({ ...base, status: 'active' })).toBe(false);
    expect(canDisable({ ...base, status: 'active' })).toBe(true);
    expect(canDisable({ ...base, status: 'expired' })).toBe(false);
    expect(canDisable({ ...base, status: 'disabled' })).toBe(false);
  });
  it('describes purchase sources', () => {
    expect(describeSource({ ...base, generation_source: 'customer' })).toBe('Online purchase');
    expect(describeSource(base)).toBe('Generated by staff');
  });
});

it('preserved sold and used vouchers cannot be edited but can be disabled', () => {
  for (const status of ['sold', 'used'] as const) {
    expect(isEditable({ ...base, status })).toBe(false);
    expect(canDisable({ ...base, status })).toBe(true);
  }
});
it('respects the server history lock even when a legacy voucher says unused', () => {
  expect(isEditable({ ...base, can_edit: false })).toBe(false);
});
